#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverywindows
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="deliverydata")]
	public partial class DATABASEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCamione(Camione instance);
    partial void UpdateCamione(Camione instance);
    partial void DeleteCamione(Camione instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertSuplidore(Suplidore instance);
    partial void UpdateSuplidore(Suplidore instance);
    partial void DeleteSuplidore(Suplidore instance);
    partial void InsertOrdene(Ordene instance);
    partial void UpdateOrdene(Ordene instance);
    partial void DeleteOrdene(Ordene instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertViaje(Viaje instance);
    partial void UpdateViaje(Viaje instance);
    partial void DeleteViaje(Viaje instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    #endregion
		
		public DATABASEDataContext() : 
				base(global::deliverywindows.Properties.Settings.Default.deliverydataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Camione> Camiones
		{
			get
			{
				return this.GetTable<Camione>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Suplidore> Suplidores
		{
			get
			{
				return this.GetTable<Suplidore>();
			}
		}
		
		public System.Data.Linq.Table<Ordene> Ordenes
		{
			get
			{
				return this.GetTable<Ordene>();
			}
		}
		
		public System.Data.Linq.Table<Transacciones_Camione> Transacciones_Camiones
		{
			get
			{
				return this.GetTable<Transacciones_Camione>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Viaje> Viajes
		{
			get
			{
				return this.GetTable<Viaje>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleados
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Camiones")]
	public partial class Camione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    #endregion
		
		public Camione()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DIRECCION1;
		
		private string _DIRECCION2;
		
		private string _CIUDAD;
		
		private string _TELEFONO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDIRECCION1Changing(string value);
    partial void OnDIRECCION1Changed();
    partial void OnDIRECCION2Changing(string value);
    partial void OnDIRECCION2Changed();
    partial void OnCIUDADChanging(string value);
    partial void OnCIUDADChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    #endregion
		
		public Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION1", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DIRECCION1
		{
			get
			{
				return this._DIRECCION1;
			}
			set
			{
				if ((this._DIRECCION1 != value))
				{
					this.OnDIRECCION1Changing(value);
					this.SendPropertyChanging();
					this._DIRECCION1 = value;
					this.SendPropertyChanged("DIRECCION1");
					this.OnDIRECCION1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION2", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DIRECCION2
		{
			get
			{
				return this._DIRECCION2;
			}
			set
			{
				if ((this._DIRECCION2 != value))
				{
					this.OnDIRECCION2Changing(value);
					this.SendPropertyChanging();
					this._DIRECCION2 = value;
					this.SendPropertyChanged("DIRECCION2");
					this.OnDIRECCION2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Suplidores")]
	public partial class Suplidore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _CIUDAD;
		
		private string _ESTADO;
		
		private string _TELEFONO;
		
		private string _DIRECCION1;
		
		private string _NOMBRECORTO;
		
		private EntitySet<Ordene> _Ordenes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnCIUDADChanging(string value);
    partial void OnCIUDADChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnDIRECCION1Changing(string value);
    partial void OnDIRECCION1Changed();
    partial void OnNOMBRECORTOChanging(string value);
    partial void OnNOMBRECORTOChanged();
    #endregion
		
		public Suplidore()
		{
			this._Ordenes = new EntitySet<Ordene>(new Action<Ordene>(this.attach_Ordenes), new Action<Ordene>(this.detach_Ordenes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(14) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION1", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DIRECCION1
		{
			get
			{
				return this._DIRECCION1;
			}
			set
			{
				if ((this._DIRECCION1 != value))
				{
					this.OnDIRECCION1Changing(value);
					this.SendPropertyChanging();
					this._DIRECCION1 = value;
					this.SendPropertyChanged("DIRECCION1");
					this.OnDIRECCION1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRECORTO", DbType="NVarChar(10)")]
		public string NOMBRECORTO
		{
			get
			{
				return this._NOMBRECORTO;
			}
			set
			{
				if ((this._NOMBRECORTO != value))
				{
					this.OnNOMBRECORTOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRECORTO = value;
					this.SendPropertyChanged("NOMBRECORTO");
					this.OnNOMBRECORTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Suplidore_Ordene", Storage="_Ordenes", ThisKey="CODIGO", OtherKey="CODIGOSUPLIDOR")]
		public EntitySet<Ordene> Ordenes
		{
			get
			{
				return this._Ordenes;
			}
			set
			{
				this._Ordenes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ordenes(Ordene entity)
		{
			this.SendPropertyChanging();
			entity.Suplidore = this;
		}
		
		private void detach_Ordenes(Ordene entity)
		{
			this.SendPropertyChanging();
			entity.Suplidore = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ordenes")]
	public partial class Ordene : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private int _CODIGOSUPLIDOR;
		
		private int _CODIGOVIAJE;
		
		private System.DateTime _FECHAORDEN;
		
		private int _ESTATUS;
		
		private string _MENSAJE;
		
		private string _PO_NOMBRE;
		
		private int _CANTIDADCAJAS;
		
		private decimal _PESOORDEN;
		
		private string _NOMBRERECIBIDOR;
		
		private System.DateTime _FECHAENTREGA;
		
		private System.Data.Linq.Binary _FIRMAENTREGA;
		
		private EntityRef<Suplidore> _Suplidore;
		
		private EntityRef<Viaje> _Viaje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnCODIGOSUPLIDORChanging(int value);
    partial void OnCODIGOSUPLIDORChanged();
    partial void OnCODIGOVIAJEChanging(int value);
    partial void OnCODIGOVIAJEChanged();
    partial void OnFECHAORDENChanging(System.DateTime value);
    partial void OnFECHAORDENChanged();
    partial void OnESTATUSChanging(int value);
    partial void OnESTATUSChanged();
    partial void OnMENSAJEChanging(string value);
    partial void OnMENSAJEChanged();
    partial void OnPO_NOMBREChanging(string value);
    partial void OnPO_NOMBREChanged();
    partial void OnCANTIDADCAJASChanging(int value);
    partial void OnCANTIDADCAJASChanged();
    partial void OnPESOORDENChanging(decimal value);
    partial void OnPESOORDENChanged();
    partial void OnNOMBRERECIBIDORChanging(string value);
    partial void OnNOMBRERECIBIDORChanged();
    partial void OnFECHAENTREGAChanging(System.DateTime value);
    partial void OnFECHAENTREGAChanged();
    partial void OnFIRMAENTREGAChanging(System.Data.Linq.Binary value);
    partial void OnFIRMAENTREGAChanged();
    #endregion
		
		public Ordene()
		{
			this._Suplidore = default(EntityRef<Suplidore>);
			this._Viaje = default(EntityRef<Viaje>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOSUPLIDOR", DbType="Int NOT NULL")]
		public int CODIGOSUPLIDOR
		{
			get
			{
				return this._CODIGOSUPLIDOR;
			}
			set
			{
				if ((this._CODIGOSUPLIDOR != value))
				{
					if (this._Suplidore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGOSUPLIDORChanging(value);
					this.SendPropertyChanging();
					this._CODIGOSUPLIDOR = value;
					this.SendPropertyChanged("CODIGOSUPLIDOR");
					this.OnCODIGOSUPLIDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOVIAJE", DbType="Int NOT NULL")]
		public int CODIGOVIAJE
		{
			get
			{
				return this._CODIGOVIAJE;
			}
			set
			{
				if ((this._CODIGOVIAJE != value))
				{
					if (this._Viaje.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGOVIAJEChanging(value);
					this.SendPropertyChanging();
					this._CODIGOVIAJE = value;
					this.SendPropertyChanged("CODIGOVIAJE");
					this.OnCODIGOVIAJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAORDEN", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAORDEN
		{
			get
			{
				return this._FECHAORDEN;
			}
			set
			{
				if ((this._FECHAORDEN != value))
				{
					this.OnFECHAORDENChanging(value);
					this.SendPropertyChanging();
					this._FECHAORDEN = value;
					this.SendPropertyChanged("FECHAORDEN");
					this.OnFECHAORDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTATUS", DbType="Int NOT NULL")]
		public int ESTATUS
		{
			get
			{
				return this._ESTATUS;
			}
			set
			{
				if ((this._ESTATUS != value))
				{
					this.OnESTATUSChanging(value);
					this.SendPropertyChanging();
					this._ESTATUS = value;
					this.SendPropertyChanged("ESTATUS");
					this.OnESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSAJE", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MENSAJE
		{
			get
			{
				return this._MENSAJE;
			}
			set
			{
				if ((this._MENSAJE != value))
				{
					this.OnMENSAJEChanging(value);
					this.SendPropertyChanging();
					this._MENSAJE = value;
					this.SendPropertyChanged("MENSAJE");
					this.OnMENSAJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_NOMBRE", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string PO_NOMBRE
		{
			get
			{
				return this._PO_NOMBRE;
			}
			set
			{
				if ((this._PO_NOMBRE != value))
				{
					this.OnPO_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._PO_NOMBRE = value;
					this.SendPropertyChanged("PO_NOMBRE");
					this.OnPO_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDADCAJAS", DbType="Int NOT NULL")]
		public int CANTIDADCAJAS
		{
			get
			{
				return this._CANTIDADCAJAS;
			}
			set
			{
				if ((this._CANTIDADCAJAS != value))
				{
					this.OnCANTIDADCAJASChanging(value);
					this.SendPropertyChanging();
					this._CANTIDADCAJAS = value;
					this.SendPropertyChanged("CANTIDADCAJAS");
					this.OnCANTIDADCAJASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PESOORDEN", DbType="Decimal(18,2) NOT NULL")]
		public decimal PESOORDEN
		{
			get
			{
				return this._PESOORDEN;
			}
			set
			{
				if ((this._PESOORDEN != value))
				{
					this.OnPESOORDENChanging(value);
					this.SendPropertyChanging();
					this._PESOORDEN = value;
					this.SendPropertyChanged("PESOORDEN");
					this.OnPESOORDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRERECIBIDOR", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NOMBRERECIBIDOR
		{
			get
			{
				return this._NOMBRERECIBIDOR;
			}
			set
			{
				if ((this._NOMBRERECIBIDOR != value))
				{
					this.OnNOMBRERECIBIDORChanging(value);
					this.SendPropertyChanging();
					this._NOMBRERECIBIDOR = value;
					this.SendPropertyChanged("NOMBRERECIBIDOR");
					this.OnNOMBRERECIBIDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAENTREGA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAENTREGA
		{
			get
			{
				return this._FECHAENTREGA;
			}
			set
			{
				if ((this._FECHAENTREGA != value))
				{
					this.OnFECHAENTREGAChanging(value);
					this.SendPropertyChanging();
					this._FECHAENTREGA = value;
					this.SendPropertyChanged("FECHAENTREGA");
					this.OnFECHAENTREGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMAENTREGA", DbType="Binary(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FIRMAENTREGA
		{
			get
			{
				return this._FIRMAENTREGA;
			}
			set
			{
				if ((this._FIRMAENTREGA != value))
				{
					this.OnFIRMAENTREGAChanging(value);
					this.SendPropertyChanging();
					this._FIRMAENTREGA = value;
					this.SendPropertyChanged("FIRMAENTREGA");
					this.OnFIRMAENTREGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Suplidore_Ordene", Storage="_Suplidore", ThisKey="CODIGOSUPLIDOR", OtherKey="CODIGO", IsForeignKey=true)]
		public Suplidore Suplidore
		{
			get
			{
				return this._Suplidore.Entity;
			}
			set
			{
				Suplidore previousValue = this._Suplidore.Entity;
				if (((previousValue != value) 
							|| (this._Suplidore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Suplidore.Entity = null;
						previousValue.Ordenes.Remove(this);
					}
					this._Suplidore.Entity = value;
					if ((value != null))
					{
						value.Ordenes.Add(this);
						this._CODIGOSUPLIDOR = value.CODIGO;
					}
					else
					{
						this._CODIGOSUPLIDOR = default(int);
					}
					this.SendPropertyChanged("Suplidore");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Viaje_Ordene", Storage="_Viaje", ThisKey="CODIGOVIAJE", OtherKey="CODIGO", IsForeignKey=true)]
		public Viaje Viaje
		{
			get
			{
				return this._Viaje.Entity;
			}
			set
			{
				Viaje previousValue = this._Viaje.Entity;
				if (((previousValue != value) 
							|| (this._Viaje.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Viaje.Entity = null;
						previousValue.Ordenes.Remove(this);
					}
					this._Viaje.Entity = value;
					if ((value != null))
					{
						value.Ordenes.Add(this);
						this._CODIGOVIAJE = value.CODIGO;
					}
					else
					{
						this._CODIGOVIAJE = default(int);
					}
					this.SendPropertyChanged("Viaje");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transacciones_Camiones")]
	public partial class Transacciones_Camione
	{
		
		private int _CODIGOVIAJE;
		
		private int _CODIGOCAMION;
		
		private decimal _ODOMETRO;
		
		private System.DateTime _FECHATRANSACCION;
		
		private int _CODIGOEMPLEADO;
		
		private System.Data.Linq.Binary _FIRMA;
		
		public Transacciones_Camione()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOVIAJE", DbType="Int NOT NULL")]
		public int CODIGOVIAJE
		{
			get
			{
				return this._CODIGOVIAJE;
			}
			set
			{
				if ((this._CODIGOVIAJE != value))
				{
					this._CODIGOVIAJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOCAMION", DbType="Int NOT NULL")]
		public int CODIGOCAMION
		{
			get
			{
				return this._CODIGOCAMION;
			}
			set
			{
				if ((this._CODIGOCAMION != value))
				{
					this._CODIGOCAMION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODOMETRO", DbType="Decimal(18,0) NOT NULL")]
		public decimal ODOMETRO
		{
			get
			{
				return this._ODOMETRO;
			}
			set
			{
				if ((this._ODOMETRO != value))
				{
					this._ODOMETRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHATRANSACCION", DbType="DateTime NOT NULL")]
		public System.DateTime FECHATRANSACCION
		{
			get
			{
				return this._FECHATRANSACCION;
			}
			set
			{
				if ((this._FECHATRANSACCION != value))
				{
					this._FECHATRANSACCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOEMPLEADO", DbType="Int NOT NULL")]
		public int CODIGOEMPLEADO
		{
			get
			{
				return this._CODIGOEMPLEADO;
			}
			set
			{
				if ((this._CODIGOEMPLEADO != value))
				{
					this._CODIGOEMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMA", DbType="Binary(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FIRMA
		{
			get
			{
				return this._FIRMA;
			}
			set
			{
				if ((this._FIRMA != value))
				{
					this._FIRMA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _USUARIO1;
		
		private string _CLAVE;
		
		private string _TIPOUSUARIO;
		
		private int _SINCRONIZA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnUSUARIO1Changing(string value);
    partial void OnUSUARIO1Changed();
    partial void OnCLAVEChanging(string value);
    partial void OnCLAVEChanged();
    partial void OnTIPOUSUARIOChanging(string value);
    partial void OnTIPOUSUARIOChanged();
    partial void OnSINCRONIZAChanging(int value);
    partial void OnSINCRONIZAChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUARIO", Storage="_USUARIO1", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string USUARIO1
		{
			get
			{
				return this._USUARIO1;
			}
			set
			{
				if ((this._USUARIO1 != value))
				{
					this.OnUSUARIO1Changing(value);
					this.SendPropertyChanging();
					this._USUARIO1 = value;
					this.SendPropertyChanged("USUARIO1");
					this.OnUSUARIO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVE", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string CLAVE
		{
			get
			{
				return this._CLAVE;
			}
			set
			{
				if ((this._CLAVE != value))
				{
					this.OnCLAVEChanging(value);
					this.SendPropertyChanging();
					this._CLAVE = value;
					this.SendPropertyChanged("CLAVE");
					this.OnCLAVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOUSUARIO", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string TIPOUSUARIO
		{
			get
			{
				return this._TIPOUSUARIO;
			}
			set
			{
				if ((this._TIPOUSUARIO != value))
				{
					this.OnTIPOUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._TIPOUSUARIO = value;
					this.SendPropertyChanged("TIPOUSUARIO");
					this.OnTIPOUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SINCRONIZA", DbType="Int NOT NULL")]
		public int SINCRONIZA
		{
			get
			{
				return this._SINCRONIZA;
			}
			set
			{
				if ((this._SINCRONIZA != value))
				{
					this.OnSINCRONIZAChanging(value);
					this.SendPropertyChanging();
					this._SINCRONIZA = value;
					this.SendPropertyChanged("SINCRONIZA");
					this.OnSINCRONIZAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Viajes")]
	public partial class Viaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private System.DateTime _FECHAVIAJE;
		
		private int _ESTATUS;
		
		private EntitySet<Ordene> _Ordenes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnFECHAVIAJEChanging(System.DateTime value);
    partial void OnFECHAVIAJEChanged();
    partial void OnESTATUSChanging(int value);
    partial void OnESTATUSChanged();
    #endregion
		
		public Viaje()
		{
			this._Ordenes = new EntitySet<Ordene>(new Action<Ordene>(this.attach_Ordenes), new Action<Ordene>(this.detach_Ordenes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAVIAJE", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAVIAJE
		{
			get
			{
				return this._FECHAVIAJE;
			}
			set
			{
				if ((this._FECHAVIAJE != value))
				{
					this.OnFECHAVIAJEChanging(value);
					this.SendPropertyChanging();
					this._FECHAVIAJE = value;
					this.SendPropertyChanged("FECHAVIAJE");
					this.OnFECHAVIAJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTATUS", DbType="Int NOT NULL")]
		public int ESTATUS
		{
			get
			{
				return this._ESTATUS;
			}
			set
			{
				if ((this._ESTATUS != value))
				{
					this.OnESTATUSChanging(value);
					this.SendPropertyChanging();
					this._ESTATUS = value;
					this.SendPropertyChanged("ESTATUS");
					this.OnESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Viaje_Ordene", Storage="_Ordenes", ThisKey="CODIGO", OtherKey="CODIGOVIAJE")]
		public EntitySet<Ordene> Ordenes
		{
			get
			{
				return this._Ordenes;
			}
			set
			{
				this._Ordenes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ordenes(Ordene entity)
		{
			this.SendPropertyChanging();
			entity.Viaje = this;
		}
		
		private void detach_Ordenes(Ordene entity)
		{
			this.SendPropertyChanging();
			entity.Viaje = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleados")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private System.Nullable<int> _CODIGOSUPERVISOR;
		
		private string _NOMBRE;
		
		private string _DIRECCION;
		
		private string _CIUDAD;
		
		private string _TELEFONO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnCODIGOSUPERVISORChanging(System.Nullable<int> value);
    partial void OnCODIGOSUPERVISORChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnCIUDADChanging(string value);
    partial void OnCIUDADChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    #endregion
		
		public Empleado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOSUPERVISOR", DbType="Int")]
		public System.Nullable<int> CODIGOSUPERVISOR
		{
			get
			{
				return this._CODIGOSUPERVISOR;
			}
			set
			{
				if ((this._CODIGOSUPERVISOR != value))
				{
					this.OnCODIGOSUPERVISORChanging(value);
					this.SendPropertyChanging();
					this._CODIGOSUPERVISOR = value;
					this.SendPropertyChanged("CODIGOSUPERVISOR");
					this.OnCODIGOSUPERVISORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
