#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliverywindows
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="deliverydata")]
	public partial class DATABASEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCamione(Camione instance);
    partial void UpdateCamione(Camione instance);
    partial void DeleteCamione(Camione instance);
    partial void InsertCiudade(Ciudade instance);
    partial void UpdateCiudade(Ciudade instance);
    partial void DeleteCiudade(Ciudade instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertOrdene(Ordene instance);
    partial void UpdateOrdene(Ordene instance);
    partial void DeleteOrdene(Ordene instance);
    partial void InsertSuplidore(Suplidore instance);
    partial void UpdateSuplidore(Suplidore instance);
    partial void DeleteSuplidore(Suplidore instance);
    partial void InsertTransacciones_Camione(Transacciones_Camione instance);
    partial void UpdateTransacciones_Camione(Transacciones_Camione instance);
    partial void DeleteTransacciones_Camione(Transacciones_Camione instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertViaje(Viaje instance);
    partial void UpdateViaje(Viaje instance);
    partial void DeleteViaje(Viaje instance);
    partial void InsertViajes_Camion(Viajes_Camion instance);
    partial void UpdateViajes_Camion(Viajes_Camion instance);
    partial void DeleteViajes_Camion(Viajes_Camion instance);
    #endregion
		
		public DATABASEDataContext() : 
				base(global::deliverywindows.Properties.Settings.Default.deliverydataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Camione> Camiones
		{
			get
			{
				return this.GetTable<Camione>();
			}
		}
		
		public System.Data.Linq.Table<Ciudade> Ciudades
		{
			get
			{
				return this.GetTable<Ciudade>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleados
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Ordene> Ordenes
		{
			get
			{
				return this.GetTable<Ordene>();
			}
		}
		
		public System.Data.Linq.Table<Suplidore> Suplidores
		{
			get
			{
				return this.GetTable<Suplidore>();
			}
		}
		
		public System.Data.Linq.Table<Transacciones_Camione> Transacciones_Camiones
		{
			get
			{
				return this.GetTable<Transacciones_Camione>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Viaje> Viajes
		{
			get
			{
				return this.GetTable<Viaje>();
			}
		}
		
		public System.Data.Linq.Table<Viajes_Camion> Viajes_Camions
		{
			get
			{
				return this.GetTable<Viajes_Camion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Camiones")]
	public partial class Camione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private EntitySet<Viajes_Camion> _Viajes_Camions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    #endregion
		
		public Camione()
		{
			this._Viajes_Camions = new EntitySet<Viajes_Camion>(new Action<Viajes_Camion>(this.attach_Viajes_Camions), new Action<Viajes_Camion>(this.detach_Viajes_Camions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Camione_Viajes_Camion", Storage="_Viajes_Camions", ThisKey="CODIGO", OtherKey="CODIGOCAMION")]
		public EntitySet<Viajes_Camion> Viajes_Camions
		{
			get
			{
				return this._Viajes_Camions;
			}
			set
			{
				this._Viajes_Camions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Viajes_Camions(Viajes_Camion entity)
		{
			this.SendPropertyChanging();
			entity.Camione = this;
		}
		
		private void detach_Viajes_Camions(Viajes_Camion entity)
		{
			this.SendPropertyChanging();
			entity.Camione = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ciudades")]
	public partial class Ciudade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private string _ZIPCODE;
		
		private EntitySet<Cliente> _Clientes;
		
		private EntitySet<Suplidore> _Suplidores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnZIPCODEChanging(string value);
    partial void OnZIPCODEChanged();
    #endregion
		
		public Ciudade()
		{
			this._Clientes = new EntitySet<Cliente>(new Action<Cliente>(this.attach_Clientes), new Action<Cliente>(this.detach_Clientes));
			this._Suplidores = new EntitySet<Suplidore>(new Action<Suplidore>(this.attach_Suplidores), new Action<Suplidore>(this.detach_Suplidores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(100)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIPCODE", DbType="NVarChar(10)")]
		public string ZIPCODE
		{
			get
			{
				return this._ZIPCODE;
			}
			set
			{
				if ((this._ZIPCODE != value))
				{
					this.OnZIPCODEChanging(value);
					this.SendPropertyChanging();
					this._ZIPCODE = value;
					this.SendPropertyChanged("ZIPCODE");
					this.OnZIPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudade_Cliente", Storage="_Clientes", ThisKey="CODIGO", OtherKey="CIUDAD")]
		public EntitySet<Cliente> Clientes
		{
			get
			{
				return this._Clientes;
			}
			set
			{
				this._Clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudade_Suplidore", Storage="_Suplidores", ThisKey="CODIGO", OtherKey="CIUDAD")]
		public EntitySet<Suplidore> Suplidores
		{
			get
			{
				return this._Suplidores;
			}
			set
			{
				this._Suplidores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Clientes(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Ciudade = this;
		}
		
		private void detach_Clientes(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Ciudade = null;
		}
		
		private void attach_Suplidores(Suplidore entity)
		{
			this.SendPropertyChanging();
			entity.Ciudade = this;
		}
		
		private void detach_Suplidores(Suplidore entity)
		{
			this.SendPropertyChanging();
			entity.Ciudade = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DIRECCION1;
		
		private string _DIRECCION2;
		
		private int _CIUDAD;
		
		private string _TELEFONO;
		
		private EntityRef<Ciudade> _Ciudade;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDIRECCION1Changing(string value);
    partial void OnDIRECCION1Changed();
    partial void OnDIRECCION2Changing(string value);
    partial void OnDIRECCION2Changed();
    partial void OnCIUDADChanging(int value);
    partial void OnCIUDADChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    #endregion
		
		public Cliente()
		{
			this._Ciudade = default(EntityRef<Ciudade>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION1", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DIRECCION1
		{
			get
			{
				return this._DIRECCION1;
			}
			set
			{
				if ((this._DIRECCION1 != value))
				{
					this.OnDIRECCION1Changing(value);
					this.SendPropertyChanging();
					this._DIRECCION1 = value;
					this.SendPropertyChanged("DIRECCION1");
					this.OnDIRECCION1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION2", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DIRECCION2
		{
			get
			{
				return this._DIRECCION2;
			}
			set
			{
				if ((this._DIRECCION2 != value))
				{
					this.OnDIRECCION2Changing(value);
					this.SendPropertyChanging();
					this._DIRECCION2 = value;
					this.SendPropertyChanged("DIRECCION2");
					this.OnDIRECCION2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="Int NOT NULL")]
		public int CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					if (this._Ciudade.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudade_Cliente", Storage="_Ciudade", ThisKey="CIUDAD", OtherKey="CODIGO", IsForeignKey=true)]
		public Ciudade Ciudade
		{
			get
			{
				return this._Ciudade.Entity;
			}
			set
			{
				Ciudade previousValue = this._Ciudade.Entity;
				if (((previousValue != value) 
							|| (this._Ciudade.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciudade.Entity = null;
						previousValue.Clientes.Remove(this);
					}
					this._Ciudade.Entity = value;
					if ((value != null))
					{
						value.Clientes.Add(this);
						this._CIUDAD = value.CODIGO;
					}
					else
					{
						this._CIUDAD = default(int);
					}
					this.SendPropertyChanged("Ciudade");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleados")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private System.Nullable<int> _CODIGOSUPERVISOR;
		
		private string _NOMBRE;
		
		private string _DIRECCION;
		
		private string _CIUDAD;
		
		private string _TELEFONO;
		
		private int _TIPO;
		
		private EntitySet<Usuario> _Usuarios;
		
		private EntitySet<Viajes_Camion> _Viajes_Camions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnCODIGOSUPERVISORChanging(System.Nullable<int> value);
    partial void OnCODIGOSUPERVISORChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnCIUDADChanging(string value);
    partial void OnCIUDADChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnTIPOChanging(int value);
    partial void OnTIPOChanged();
    #endregion
		
		public Empleado()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			this._Viajes_Camions = new EntitySet<Viajes_Camion>(new Action<Viajes_Camion>(this.attach_Viajes_Camions), new Action<Viajes_Camion>(this.detach_Viajes_Camions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOSUPERVISOR", DbType="Int")]
		public System.Nullable<int> CODIGOSUPERVISOR
		{
			get
			{
				return this._CODIGOSUPERVISOR;
			}
			set
			{
				if ((this._CODIGOSUPERVISOR != value))
				{
					this.OnCODIGOSUPERVISORChanging(value);
					this.SendPropertyChanging();
					this._CODIGOSUPERVISOR = value;
					this.SendPropertyChanged("CODIGOSUPERVISOR");
					this.OnCODIGOSUPERVISORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="Int NOT NULL")]
		public int TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this.OnTIPOChanging(value);
					this.SendPropertyChanging();
					this._TIPO = value;
					this.SendPropertyChanged("TIPO");
					this.OnTIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Usuario", Storage="_Usuarios", ThisKey="CODIGO", OtherKey="CODIGOEMPLEADO")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Viajes_Camion", Storage="_Viajes_Camions", ThisKey="CODIGO", OtherKey="CODIGOEMPLEADO")]
		public EntitySet<Viajes_Camion> Viajes_Camions
		{
			get
			{
				return this._Viajes_Camions;
			}
			set
			{
				this._Viajes_Camions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
		
		private void attach_Viajes_Camions(Viajes_Camion entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_Viajes_Camions(Viajes_Camion entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ordenes")]
	public partial class Ordene : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private int _CODIGOSUPLIDOR;
		
		private int _CODIGOCLIENTE;
		
		private int _CODIGOVIAJE;
		
		private System.DateTime _FECHAORDEN;
		
		private int _ESTATUS;
		
		private string _MENSAJE;
		
		private string _PO_NOMBRE;
		
		private int _CANTIDADCAJAS;
		
		private decimal _PESOORDEN;
		
		private string _NOMBRERECIBIDOR;
		
		private System.DateTime _FECHAENTREGA;
		
		private System.Data.Linq.Binary _FIRMAENTREGA;
		
		private EntitySet<Transacciones_Camione> _Transacciones_Camiones;
		
		private EntityRef<Suplidore> _Suplidore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnCODIGOSUPLIDORChanging(int value);
    partial void OnCODIGOSUPLIDORChanged();
    partial void OnCODIGOCLIENTEChanging(int value);
    partial void OnCODIGOCLIENTEChanged();
    partial void OnCODIGOVIAJEChanging(int value);
    partial void OnCODIGOVIAJEChanged();
    partial void OnFECHAORDENChanging(System.DateTime value);
    partial void OnFECHAORDENChanged();
    partial void OnESTATUSChanging(int value);
    partial void OnESTATUSChanged();
    partial void OnMENSAJEChanging(string value);
    partial void OnMENSAJEChanged();
    partial void OnPO_NOMBREChanging(string value);
    partial void OnPO_NOMBREChanged();
    partial void OnCANTIDADCAJASChanging(int value);
    partial void OnCANTIDADCAJASChanged();
    partial void OnPESOORDENChanging(decimal value);
    partial void OnPESOORDENChanged();
    partial void OnNOMBRERECIBIDORChanging(string value);
    partial void OnNOMBRERECIBIDORChanged();
    partial void OnFECHAENTREGAChanging(System.DateTime value);
    partial void OnFECHAENTREGAChanged();
    partial void OnFIRMAENTREGAChanging(System.Data.Linq.Binary value);
    partial void OnFIRMAENTREGAChanged();
    #endregion
		
		public Ordene()
		{
			this._Transacciones_Camiones = new EntitySet<Transacciones_Camione>(new Action<Transacciones_Camione>(this.attach_Transacciones_Camiones), new Action<Transacciones_Camione>(this.detach_Transacciones_Camiones));
			this._Suplidore = default(EntityRef<Suplidore>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOSUPLIDOR", DbType="Int NOT NULL")]
		public int CODIGOSUPLIDOR
		{
			get
			{
				return this._CODIGOSUPLIDOR;
			}
			set
			{
				if ((this._CODIGOSUPLIDOR != value))
				{
					if (this._Suplidore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGOSUPLIDORChanging(value);
					this.SendPropertyChanging();
					this._CODIGOSUPLIDOR = value;
					this.SendPropertyChanged("CODIGOSUPLIDOR");
					this.OnCODIGOSUPLIDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOCLIENTE", DbType="Int NOT NULL")]
		public int CODIGOCLIENTE
		{
			get
			{
				return this._CODIGOCLIENTE;
			}
			set
			{
				if ((this._CODIGOCLIENTE != value))
				{
					this.OnCODIGOCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CODIGOCLIENTE = value;
					this.SendPropertyChanged("CODIGOCLIENTE");
					this.OnCODIGOCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOVIAJE", DbType="Int NOT NULL")]
		public int CODIGOVIAJE
		{
			get
			{
				return this._CODIGOVIAJE;
			}
			set
			{
				if ((this._CODIGOVIAJE != value))
				{
					this.OnCODIGOVIAJEChanging(value);
					this.SendPropertyChanging();
					this._CODIGOVIAJE = value;
					this.SendPropertyChanged("CODIGOVIAJE");
					this.OnCODIGOVIAJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAORDEN", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAORDEN
		{
			get
			{
				return this._FECHAORDEN;
			}
			set
			{
				if ((this._FECHAORDEN != value))
				{
					this.OnFECHAORDENChanging(value);
					this.SendPropertyChanging();
					this._FECHAORDEN = value;
					this.SendPropertyChanged("FECHAORDEN");
					this.OnFECHAORDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTATUS", DbType="Int NOT NULL")]
		public int ESTATUS
		{
			get
			{
				return this._ESTATUS;
			}
			set
			{
				if ((this._ESTATUS != value))
				{
					this.OnESTATUSChanging(value);
					this.SendPropertyChanging();
					this._ESTATUS = value;
					this.SendPropertyChanged("ESTATUS");
					this.OnESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSAJE", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MENSAJE
		{
			get
			{
				return this._MENSAJE;
			}
			set
			{
				if ((this._MENSAJE != value))
				{
					this.OnMENSAJEChanging(value);
					this.SendPropertyChanging();
					this._MENSAJE = value;
					this.SendPropertyChanged("MENSAJE");
					this.OnMENSAJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_NOMBRE", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string PO_NOMBRE
		{
			get
			{
				return this._PO_NOMBRE;
			}
			set
			{
				if ((this._PO_NOMBRE != value))
				{
					this.OnPO_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._PO_NOMBRE = value;
					this.SendPropertyChanged("PO_NOMBRE");
					this.OnPO_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDADCAJAS", DbType="Int NOT NULL")]
		public int CANTIDADCAJAS
		{
			get
			{
				return this._CANTIDADCAJAS;
			}
			set
			{
				if ((this._CANTIDADCAJAS != value))
				{
					this.OnCANTIDADCAJASChanging(value);
					this.SendPropertyChanging();
					this._CANTIDADCAJAS = value;
					this.SendPropertyChanged("CANTIDADCAJAS");
					this.OnCANTIDADCAJASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PESOORDEN", DbType="Decimal(18,2) NOT NULL")]
		public decimal PESOORDEN
		{
			get
			{
				return this._PESOORDEN;
			}
			set
			{
				if ((this._PESOORDEN != value))
				{
					this.OnPESOORDENChanging(value);
					this.SendPropertyChanging();
					this._PESOORDEN = value;
					this.SendPropertyChanged("PESOORDEN");
					this.OnPESOORDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRERECIBIDOR", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NOMBRERECIBIDOR
		{
			get
			{
				return this._NOMBRERECIBIDOR;
			}
			set
			{
				if ((this._NOMBRERECIBIDOR != value))
				{
					this.OnNOMBRERECIBIDORChanging(value);
					this.SendPropertyChanging();
					this._NOMBRERECIBIDOR = value;
					this.SendPropertyChanged("NOMBRERECIBIDOR");
					this.OnNOMBRERECIBIDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAENTREGA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAENTREGA
		{
			get
			{
				return this._FECHAENTREGA;
			}
			set
			{
				if ((this._FECHAENTREGA != value))
				{
					this.OnFECHAENTREGAChanging(value);
					this.SendPropertyChanging();
					this._FECHAENTREGA = value;
					this.SendPropertyChanged("FECHAENTREGA");
					this.OnFECHAENTREGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMAENTREGA", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FIRMAENTREGA
		{
			get
			{
				return this._FIRMAENTREGA;
			}
			set
			{
				if ((this._FIRMAENTREGA != value))
				{
					this.OnFIRMAENTREGAChanging(value);
					this.SendPropertyChanging();
					this._FIRMAENTREGA = value;
					this.SendPropertyChanged("FIRMAENTREGA");
					this.OnFIRMAENTREGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ordene_Transacciones_Camione", Storage="_Transacciones_Camiones", ThisKey="CODIGO", OtherKey="CODIGOORDEN")]
		public EntitySet<Transacciones_Camione> Transacciones_Camiones
		{
			get
			{
				return this._Transacciones_Camiones;
			}
			set
			{
				this._Transacciones_Camiones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Suplidore_Ordene", Storage="_Suplidore", ThisKey="CODIGOSUPLIDOR", OtherKey="CODIGO", IsForeignKey=true)]
		public Suplidore Suplidore
		{
			get
			{
				return this._Suplidore.Entity;
			}
			set
			{
				Suplidore previousValue = this._Suplidore.Entity;
				if (((previousValue != value) 
							|| (this._Suplidore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Suplidore.Entity = null;
						previousValue.Ordenes.Remove(this);
					}
					this._Suplidore.Entity = value;
					if ((value != null))
					{
						value.Ordenes.Add(this);
						this._CODIGOSUPLIDOR = value.CODIGO;
					}
					else
					{
						this._CODIGOSUPLIDOR = default(int);
					}
					this.SendPropertyChanged("Suplidore");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transacciones_Camiones(Transacciones_Camione entity)
		{
			this.SendPropertyChanging();
			entity.Ordene = this;
		}
		
		private void detach_Transacciones_Camiones(Transacciones_Camione entity)
		{
			this.SendPropertyChanging();
			entity.Ordene = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Suplidores")]
	public partial class Suplidore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private int _CIUDAD;
		
		private string _ESTADO;
		
		private string _TELEFONO;
		
		private string _DIRECCION1;
		
		private string _NOMBRECORTO;
		
		private EntitySet<Ordene> _Ordenes;
		
		private EntityRef<Ciudade> _Ciudade;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnCIUDADChanging(int value);
    partial void OnCIUDADChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnDIRECCION1Changing(string value);
    partial void OnDIRECCION1Changed();
    partial void OnNOMBRECORTOChanging(string value);
    partial void OnNOMBRECORTOChanged();
    #endregion
		
		public Suplidore()
		{
			this._Ordenes = new EntitySet<Ordene>(new Action<Ordene>(this.attach_Ordenes), new Action<Ordene>(this.detach_Ordenes));
			this._Ciudade = default(EntityRef<Ciudade>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="Int NOT NULL")]
		public int CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					if (this._Ciudade.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(14) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION1", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DIRECCION1
		{
			get
			{
				return this._DIRECCION1;
			}
			set
			{
				if ((this._DIRECCION1 != value))
				{
					this.OnDIRECCION1Changing(value);
					this.SendPropertyChanging();
					this._DIRECCION1 = value;
					this.SendPropertyChanged("DIRECCION1");
					this.OnDIRECCION1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRECORTO", DbType="NVarChar(10)")]
		public string NOMBRECORTO
		{
			get
			{
				return this._NOMBRECORTO;
			}
			set
			{
				if ((this._NOMBRECORTO != value))
				{
					this.OnNOMBRECORTOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRECORTO = value;
					this.SendPropertyChanged("NOMBRECORTO");
					this.OnNOMBRECORTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Suplidore_Ordene", Storage="_Ordenes", ThisKey="CODIGO", OtherKey="CODIGOSUPLIDOR")]
		public EntitySet<Ordene> Ordenes
		{
			get
			{
				return this._Ordenes;
			}
			set
			{
				this._Ordenes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudade_Suplidore", Storage="_Ciudade", ThisKey="CIUDAD", OtherKey="CODIGO", IsForeignKey=true)]
		public Ciudade Ciudade
		{
			get
			{
				return this._Ciudade.Entity;
			}
			set
			{
				Ciudade previousValue = this._Ciudade.Entity;
				if (((previousValue != value) 
							|| (this._Ciudade.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciudade.Entity = null;
						previousValue.Suplidores.Remove(this);
					}
					this._Ciudade.Entity = value;
					if ((value != null))
					{
						value.Suplidores.Add(this);
						this._CIUDAD = value.CODIGO;
					}
					else
					{
						this._CIUDAD = default(int);
					}
					this.SendPropertyChanged("Ciudade");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ordenes(Ordene entity)
		{
			this.SendPropertyChanging();
			entity.Suplidore = this;
		}
		
		private void detach_Ordenes(Ordene entity)
		{
			this.SendPropertyChanging();
			entity.Suplidore = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transacciones_Camiones")]
	public partial class Transacciones_Camione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGOORDEN;
		
		private int _CODIGOVIAJE;
		
		private decimal _ODOMETRO;
		
		private System.DateTime _FECHATRANSACCION;
		
		private System.Data.Linq.Binary _FIRMA;
		
		private EntityRef<Ordene> _Ordene;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOORDENChanging(int value);
    partial void OnCODIGOORDENChanged();
    partial void OnCODIGOVIAJEChanging(int value);
    partial void OnCODIGOVIAJEChanged();
    partial void OnODOMETROChanging(decimal value);
    partial void OnODOMETROChanged();
    partial void OnFECHATRANSACCIONChanging(System.DateTime value);
    partial void OnFECHATRANSACCIONChanged();
    partial void OnFIRMAChanging(System.Data.Linq.Binary value);
    partial void OnFIRMAChanged();
    #endregion
		
		public Transacciones_Camione()
		{
			this._Ordene = default(EntityRef<Ordene>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOORDEN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGOORDEN
		{
			get
			{
				return this._CODIGOORDEN;
			}
			set
			{
				if ((this._CODIGOORDEN != value))
				{
					if (this._Ordene.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGOORDENChanging(value);
					this.SendPropertyChanging();
					this._CODIGOORDEN = value;
					this.SendPropertyChanged("CODIGOORDEN");
					this.OnCODIGOORDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOVIAJE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGOVIAJE
		{
			get
			{
				return this._CODIGOVIAJE;
			}
			set
			{
				if ((this._CODIGOVIAJE != value))
				{
					this.OnCODIGOVIAJEChanging(value);
					this.SendPropertyChanging();
					this._CODIGOVIAJE = value;
					this.SendPropertyChanged("CODIGOVIAJE");
					this.OnCODIGOVIAJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODOMETRO", DbType="Decimal(18,0) NOT NULL")]
		public decimal ODOMETRO
		{
			get
			{
				return this._ODOMETRO;
			}
			set
			{
				if ((this._ODOMETRO != value))
				{
					this.OnODOMETROChanging(value);
					this.SendPropertyChanging();
					this._ODOMETRO = value;
					this.SendPropertyChanged("ODOMETRO");
					this.OnODOMETROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHATRANSACCION", DbType="DateTime NOT NULL")]
		public System.DateTime FECHATRANSACCION
		{
			get
			{
				return this._FECHATRANSACCION;
			}
			set
			{
				if ((this._FECHATRANSACCION != value))
				{
					this.OnFECHATRANSACCIONChanging(value);
					this.SendPropertyChanging();
					this._FECHATRANSACCION = value;
					this.SendPropertyChanged("FECHATRANSACCION");
					this.OnFECHATRANSACCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMA", DbType="Binary(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FIRMA
		{
			get
			{
				return this._FIRMA;
			}
			set
			{
				if ((this._FIRMA != value))
				{
					this.OnFIRMAChanging(value);
					this.SendPropertyChanging();
					this._FIRMA = value;
					this.SendPropertyChanged("FIRMA");
					this.OnFIRMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ordene_Transacciones_Camione", Storage="_Ordene", ThisKey="CODIGOORDEN", OtherKey="CODIGO", IsForeignKey=true)]
		public Ordene Ordene
		{
			get
			{
				return this._Ordene.Entity;
			}
			set
			{
				Ordene previousValue = this._Ordene.Entity;
				if (((previousValue != value) 
							|| (this._Ordene.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ordene.Entity = null;
						previousValue.Transacciones_Camiones.Remove(this);
					}
					this._Ordene.Entity = value;
					if ((value != null))
					{
						value.Transacciones_Camiones.Add(this);
						this._CODIGOORDEN = value.CODIGO;
					}
					else
					{
						this._CODIGOORDEN = default(int);
					}
					this.SendPropertyChanged("Ordene");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private string _USUARIO1;
		
		private string _CLAVE;
		
		private string _TIPOUSUARIO;
		
		private int _SINCRONIZA;
		
		private System.Nullable<int> _CODIGOEMPLEADO;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnUSUARIO1Changing(string value);
    partial void OnUSUARIO1Changed();
    partial void OnCLAVEChanging(string value);
    partial void OnCLAVEChanged();
    partial void OnTIPOUSUARIOChanging(string value);
    partial void OnTIPOUSUARIOChanged();
    partial void OnSINCRONIZAChanging(int value);
    partial void OnSINCRONIZAChanged();
    partial void OnCODIGOEMPLEADOChanging(System.Nullable<int> value);
    partial void OnCODIGOEMPLEADOChanged();
    #endregion
		
		public Usuario()
		{
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUARIO", Storage="_USUARIO1", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string USUARIO1
		{
			get
			{
				return this._USUARIO1;
			}
			set
			{
				if ((this._USUARIO1 != value))
				{
					this.OnUSUARIO1Changing(value);
					this.SendPropertyChanging();
					this._USUARIO1 = value;
					this.SendPropertyChanged("USUARIO1");
					this.OnUSUARIO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVE", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string CLAVE
		{
			get
			{
				return this._CLAVE;
			}
			set
			{
				if ((this._CLAVE != value))
				{
					this.OnCLAVEChanging(value);
					this.SendPropertyChanging();
					this._CLAVE = value;
					this.SendPropertyChanged("CLAVE");
					this.OnCLAVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOUSUARIO", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string TIPOUSUARIO
		{
			get
			{
				return this._TIPOUSUARIO;
			}
			set
			{
				if ((this._TIPOUSUARIO != value))
				{
					this.OnTIPOUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._TIPOUSUARIO = value;
					this.SendPropertyChanged("TIPOUSUARIO");
					this.OnTIPOUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SINCRONIZA", DbType="Int NOT NULL")]
		public int SINCRONIZA
		{
			get
			{
				return this._SINCRONIZA;
			}
			set
			{
				if ((this._SINCRONIZA != value))
				{
					this.OnSINCRONIZAChanging(value);
					this.SendPropertyChanging();
					this._SINCRONIZA = value;
					this.SendPropertyChanged("SINCRONIZA");
					this.OnSINCRONIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOEMPLEADO", DbType="Int")]
		public System.Nullable<int> CODIGOEMPLEADO
		{
			get
			{
				return this._CODIGOEMPLEADO;
			}
			set
			{
				if ((this._CODIGOEMPLEADO != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGOEMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._CODIGOEMPLEADO = value;
					this.SendPropertyChanged("CODIGOEMPLEADO");
					this.OnCODIGOEMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Usuario", Storage="_Empleado", ThisKey="CODIGOEMPLEADO", OtherKey="CODIGO", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._CODIGOEMPLEADO = value.CODIGO;
					}
					else
					{
						this._CODIGOEMPLEADO = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Viajes")]
	public partial class Viaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO;
		
		private System.DateTime _FECHAVIAJE;
		
		private int _ESTATUS;
		
		private EntityRef<Viajes_Camion> _Viajes_Camion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOChanging(int value);
    partial void OnCODIGOChanged();
    partial void OnFECHAVIAJEChanging(System.DateTime value);
    partial void OnFECHAVIAJEChanged();
    partial void OnESTATUSChanging(int value);
    partial void OnESTATUSChanged();
    #endregion
		
		public Viaje()
		{
			this._Viajes_Camion = default(EntityRef<Viajes_Camion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAVIAJE", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAVIAJE
		{
			get
			{
				return this._FECHAVIAJE;
			}
			set
			{
				if ((this._FECHAVIAJE != value))
				{
					this.OnFECHAVIAJEChanging(value);
					this.SendPropertyChanging();
					this._FECHAVIAJE = value;
					this.SendPropertyChanged("FECHAVIAJE");
					this.OnFECHAVIAJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTATUS", DbType="Int NOT NULL")]
		public int ESTATUS
		{
			get
			{
				return this._ESTATUS;
			}
			set
			{
				if ((this._ESTATUS != value))
				{
					this.OnESTATUSChanging(value);
					this.SendPropertyChanging();
					this._ESTATUS = value;
					this.SendPropertyChanged("ESTATUS");
					this.OnESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Viaje_Viajes_Camion", Storage="_Viajes_Camion", ThisKey="CODIGO", OtherKey="CODIGOVIAJE", IsUnique=true, IsForeignKey=false)]
		public Viajes_Camion Viajes_Camion
		{
			get
			{
				return this._Viajes_Camion.Entity;
			}
			set
			{
				Viajes_Camion previousValue = this._Viajes_Camion.Entity;
				if (((previousValue != value) 
							|| (this._Viajes_Camion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Viajes_Camion.Entity = null;
						previousValue.Viaje = null;
					}
					this._Viajes_Camion.Entity = value;
					if ((value != null))
					{
						value.Viaje = this;
					}
					this.SendPropertyChanged("Viajes_Camion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Viajes_Camion")]
	public partial class Viajes_Camion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGOVIAJE;
		
		private int _CODIGOCAMION;
		
		private int _CODIGOEMPLEADO;
		
		private EntityRef<Camione> _Camione;
		
		private EntityRef<Empleado> _Empleado;
		
		private EntityRef<Viaje> _Viaje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGOVIAJEChanging(int value);
    partial void OnCODIGOVIAJEChanged();
    partial void OnCODIGOCAMIONChanging(int value);
    partial void OnCODIGOCAMIONChanged();
    partial void OnCODIGOEMPLEADOChanging(int value);
    partial void OnCODIGOEMPLEADOChanged();
    #endregion
		
		public Viajes_Camion()
		{
			this._Camione = default(EntityRef<Camione>);
			this._Empleado = default(EntityRef<Empleado>);
			this._Viaje = default(EntityRef<Viaje>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOVIAJE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODIGOVIAJE
		{
			get
			{
				return this._CODIGOVIAJE;
			}
			set
			{
				if ((this._CODIGOVIAJE != value))
				{
					if (this._Viaje.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGOVIAJEChanging(value);
					this.SendPropertyChanging();
					this._CODIGOVIAJE = value;
					this.SendPropertyChanged("CODIGOVIAJE");
					this.OnCODIGOVIAJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOCAMION", DbType="Int NOT NULL")]
		public int CODIGOCAMION
		{
			get
			{
				return this._CODIGOCAMION;
			}
			set
			{
				if ((this._CODIGOCAMION != value))
				{
					if (this._Camione.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGOCAMIONChanging(value);
					this.SendPropertyChanging();
					this._CODIGOCAMION = value;
					this.SendPropertyChanged("CODIGOCAMION");
					this.OnCODIGOCAMIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOEMPLEADO", DbType="Int NOT NULL")]
		public int CODIGOEMPLEADO
		{
			get
			{
				return this._CODIGOEMPLEADO;
			}
			set
			{
				if ((this._CODIGOEMPLEADO != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGOEMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._CODIGOEMPLEADO = value;
					this.SendPropertyChanged("CODIGOEMPLEADO");
					this.OnCODIGOEMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Camione_Viajes_Camion", Storage="_Camione", ThisKey="CODIGOCAMION", OtherKey="CODIGO", IsForeignKey=true)]
		public Camione Camione
		{
			get
			{
				return this._Camione.Entity;
			}
			set
			{
				Camione previousValue = this._Camione.Entity;
				if (((previousValue != value) 
							|| (this._Camione.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Camione.Entity = null;
						previousValue.Viajes_Camions.Remove(this);
					}
					this._Camione.Entity = value;
					if ((value != null))
					{
						value.Viajes_Camions.Add(this);
						this._CODIGOCAMION = value.CODIGO;
					}
					else
					{
						this._CODIGOCAMION = default(int);
					}
					this.SendPropertyChanged("Camione");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Viajes_Camion", Storage="_Empleado", ThisKey="CODIGOEMPLEADO", OtherKey="CODIGO", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.Viajes_Camions.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.Viajes_Camions.Add(this);
						this._CODIGOEMPLEADO = value.CODIGO;
					}
					else
					{
						this._CODIGOEMPLEADO = default(int);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Viaje_Viajes_Camion", Storage="_Viaje", ThisKey="CODIGOVIAJE", OtherKey="CODIGO", IsForeignKey=true)]
		public Viaje Viaje
		{
			get
			{
				return this._Viaje.Entity;
			}
			set
			{
				Viaje previousValue = this._Viaje.Entity;
				if (((previousValue != value) 
							|| (this._Viaje.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Viaje.Entity = null;
						previousValue.Viajes_Camion = null;
					}
					this._Viaje.Entity = value;
					if ((value != null))
					{
						value.Viajes_Camion = this;
						this._CODIGOVIAJE = value.CODIGO;
					}
					else
					{
						this._CODIGOVIAJE = default(int);
					}
					this.SendPropertyChanged("Viaje");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
